
'use client';
import Image from 'next/image';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Mail, Target, Building2, TrendingUp, Users, Vote, Search, Lightbulb, Check } from 'lucide-react';
import { useLanguage } from '@/contexts/language-context';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import Link from 'next/link';
import { motion } from 'framer-motion';

const content = {
  es: {
    badge: "Análisis de Datos",
    title: "Quest",
    subtitle: "La plataforma de inteligencia para la <strong>toma de decisiones</strong> en el sector público. Gobierna con datos, no con intuición.",
    cta2025Button: "Acceder al Dashboard",
    videoTitle: "Quest en Acción",
    useCasesTitle: "Descubre lo que Quest puede hacer por ti",
    useCasesSubtitle: "Selecciona tu área para ver cómo Quest transforma datos en decisiones estratégicas.",
    tabs: {
      governments: "Para Gobiernos",
      campaigns: "Para Campañas Electorales"
    },
    govPoints: [
      { icon: <Building2 className="text-primary size-8" />, title: "Gestión Eficiente", description: "Visualiza el estado de tu gestión y el impacto de tus políticas en tiempo real." },
      { icon: <TrendingUp className="text-primary size-8" />, title: "Anticipación de Crisis", description: "Detecta tendencias y patrones para prever conflictos sociales o económicos." },
      { icon: <Users className="text-primary size-8" />, title: "Conocimiento Ciudadano", description: "Comprende las demandas y el sentir de la población para guiar tus acciones." },
      { icon: <Lightbulb className="text-primary size-8" />, title: "Recomendaciones de IA", description: "Recibe sugerencias de políticas públicas basadas en evidencia y datos." },
    ],
    campaignPoints: [
        { icon: <Target className="text-primary size-8" />, title: "Optimización de Recursos", description: "Identifica las áreas geográficas clave para enfocar tus esfuerzos y tu presupuesto." },
        { icon: <Vote className="text-primary size-8" />, title: "Segmentación de Votantes", description: "Conoce el perfil y las preocupaciones de distintos segmentos del electorado." },
        { icon: <Search className="text-primary size-8" />, title: "Análisis de Competencia", description: "Monitorea el posicionamiento y la estrategia de tus adversarios." },
        { icon: <Lightbulb className="text-primary size-8" />, title: "Mensajes Efectivos", description: "Ajusta tu discurso con recomendaciones de IA para conectar con cada audiencia." },
    ],
    caseTitle: "🇦🇷 Caso de Éxito: Elecciones Presidenciales de Argentina 2023",
    caseDescription: "<p>Realizamos un estudio diario entre enero y noviembre de 2023, recopilando más de <strong>7,100,000 puntos de datos</strong> sobre los candidatos presidenciales en Argentina, cubriendo todo el país.</p><p class='mt-2'>Esto proporcionó una <strong>visión sin precedentes</strong> del sentimiento y las tendencias de los votantes, demostrando la fiabilidad y el poder de Quest en entornos complejos.</p>",
    ctaTitle: "¿Listo para tomar decisiones basadas en datos?",
    ctaSubtitle: "Descubre cómo Quest puede darte la visión estratégica que necesitas para anticiparte al futuro.",
    ctaButton: "Solicita una presentación de Quest",
    loginButton: "Iniciar Sesión",
  },
  en: {
    badge: "Data Analysis",
    title: "Quest",
    subtitle: "The intelligence platform for <strong>decision-making</strong> in the public sector. Govern with data, not intuition.",
    cta2025Button: "Access Dashboard",
    videoTitle: "Quest in Action",
    useCasesTitle: "Discover what Quest can do for you",
    useCasesSubtitle: "Select your area to see how Quest turns data into strategic decisions.",
    tabs: {
      governments: "For Governments",
      campaigns: "For Electoral Campaigns"
    },
    govPoints: [
      { icon: <Building2 className="text-primary size-8" />, title: "Efficient Management", description: "Visualize the state of your administration and the impact of your policies in real-time." },
      { icon: <TrendingUp className="text-primary size-8" />, title: "Crisis Anticipation", description: "Detect trends and patterns to foresee social or economic conflicts." },
      { icon: <Users className="text-primary size-8" />, title: "Citizen Insight", description: "Understand the demands and sentiments of the population to guide your actions." },
      { icon: <Lightbulb className="text-primary size-8" />, title: "AI Recommendations", description: "Receive evidence-based public policy suggestions generated by AI." },
    ],
    campaignPoints: [
        { icon: <Target className="text-primary size-8" />, title: "Resource Optimization", description: "Identify key geographical areas to focus your efforts and budget." },
        { icon: <Vote className="text-primary size-8" />, title: "Voter Segmentation", description: "Know the profile and concerns of different voter segments." },
        { icon: <Search className="text-primary size-8" />, title: "Competitor Analysis", description: "Monitor the positioning and strategy of your opponents." },
        { icon: <Lightbulb className="text-primary size-8" />, title: "Effective Messaging", description: "Adjust your discourse with AI recommendations to connect with each audience." },
    ],
    caseTitle: "🇦🇷 Success Case: Argentine Presidential Elections 2023",
    caseDescription: "<p>A daily study was conducted between January and November 2023, collecting more than <strong>7,100,000 data points</strong> on presidential candidates in Argentina, covering the entire country.</p><p class='mt-2'>This provided <strong>unprecedented insight</strong> into voter sentiment and trends, demonstrating Quest's reliability and power in complex environments.</p>",
    ctaTitle: "Ready to make data-driven decisions?",
    ctaSubtitle: "Discover how Quest can give you the strategic insight you need to anticipate the future.",
    ctaButton: "Request a Quest presentation",
    loginButton: "Login",
  }
}

export default function QuestPage() {
  const { language } = useLanguage();
  const c = content[language];

  const generateMailto = () => {
    const subject = `Solicitud de presentación de ${c.title}`;
    const body = `Estimado Juan,\n\nMe gustaría coordinar una reunión para una presentación de ${c.title}.\n\nMe interesa porque...\n\nSaludos.`;
    return `mailto:juan.ulian@pluscompol.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const strategicAdvantages = [
    { title: 'Base de Encuestas Centralizada', text: 'Accedé a la base de encuestas más grande del país.' },
    { title: 'Comparación de Metodologías', text: 'Compará estudios y metodologías de todas las consultoras.' },
    { title: 'Análisis de Tendencias', text: 'Seguí día a día las tendencias de voto y su evolución.' },
    { title: 'Informes por Provincia', text: 'Explorá informes y estados de situación por provincia.' },
    { title: 'Visualización Clara', text: 'Visualizá datos complejos con claridad y precisión.' },
    { title: 'IA Generativa', text: 'Informes profesionales generados por inteligencia artificial.' },
  ]

  return (
    <>
      <header className="py-20 bg-primary/10 relative" style={{backgroundImage: "url('/backgrounds/titulos.jpeg')", backgroundSize: 'cover', backgroundPosition: 'center'}}>
        <div className="container mx-auto px-4 text-center">
          <div className="flex flex-col items-center">
            <Image src="/logo/quest.png" alt="Quest Logo" width={80} height={80} className="mb-4" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold font-headline text-white">{c.title}</h1>
          <Badge className="mt-4">{c.badge}</Badge>
          <p className="mt-4 text-lg text-white/90 max-w-2xl mx-auto" dangerouslySetInnerHTML={{ __html: c.subtitle }}/>
        </div>
      </header>
      <main>
        {/* Sección Hero Unificada - CTA Principal */}
        <section className="relative py-20 md:py-32 overflow-hidden" style={{backgroundImage: "url('/backgrounds/cuerpo.jpeg')", backgroundSize: 'cover', backgroundPosition: 'center'}}>
          {/* Overlay gradient para mejorar contraste */}
          <div className="absolute inset-0 bg-gradient-to-b from-background/95 via-background/90 to-background/95" />

          <div className="container mx-auto px-4 relative z-10">
            {/* Card principal con borde sutil */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.8 }}
              className="max-w-6xl mx-auto"
            >
              <div className="rounded-3xl border-2 border-primary/20 bg-gradient-to-br from-background/80 via-background/60 to-primary/5 backdrop-blur-xl shadow-2xl p-8 md:p-16">
                {/* Título principal con efecto de aparecer */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: 0.2 }}
                  className="text-center mb-12"
                >
                  <div className="inline-block px-4 py-2 bg-primary/10 rounded-full mb-6">
                    <span className="text-sm font-semibold text-primary">Elecciones Legislativas Argentina 2025</span>
                  </div>
                  <h2 className="text-4xl md:text-6xl font-bold font-headline tracking-tight mb-6 bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">
                    Quest. Inteligencia que decide.
                  </h2>
                  <p className="text-xl md:text-2xl text-muted-foreground max-w-3xl mx-auto leading-relaxed">
                    La herramienta que transforma datos complejos en decisiones claras.
                  </p>
                </motion.div>

                {/* Features Grid con animación escalonada */}
                <motion.div
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.8, delay: 0.4 }}
                  className="max-w-4xl mx-auto mb-12"
                >
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {strategicAdvantages.map((advantage, index) => (
                      <motion.div
                        key={index}
                        initial={{ opacity: 0, x: -20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5, delay: 0.5 + index * 0.1 }}
                        className="group flex items-start gap-4 p-4 rounded-xl hover:bg-primary/5 transition-all duration-300 hover:scale-[1.02]"
                      >
                        <div className="flex-shrink-0 mt-1">
                          <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary/20 to-primary/10 flex items-center justify-center group-hover:scale-110 transition-transform duration-300 shadow-lg">
                            <Check className="w-5 h-5 text-primary" strokeWidth={3} />
                          </div>
                        </div>
                        <div className="flex-1">
                          <h3 className="font-bold text-base md:text-lg mb-1 group-hover:text-primary transition-colors">
                            {advantage.title}
                          </h3>
                          <p className="text-muted-foreground text-sm leading-relaxed">
                            {advantage.text}
                          </p>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </motion.div>

                {/* Divider decorativo */}
                <div className="relative h-px bg-gradient-to-r from-transparent via-primary/30 to-transparent my-12" />

                {/* CTA Final con efecto de brillo */}
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: 0.8 }}
                  className="text-center space-y-8"
                >
                  <div className="space-y-4">
                    <h3 className="text-3xl md:text-4xl font-bold font-headline tracking-tight">
                      Simple. Potente. Preciso.
                    </h3>
                    <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto">
                      Quest elimina la complejidad del análisis político. Lo que antes tomaba días, ahora toma minutos.
                    </p>
                  </div>

                  <div className="flex flex-col sm:flex-row gap-4 justify-center items-center pt-6">
                    <Button asChild size="lg" className="text-lg px-10 py-7 rounded-xl shadow-lg hover:shadow-2xl transition-all duration-300 hover:scale-105 bg-gradient-to-r from-primary to-primary/80">
                      <Link href="/products/quest/login" className="flex items-center gap-2">
                        Acceder al Dashboard
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                        </svg>
                      </Link>
                    </Button>
                  </div>

                  <p className="text-sm text-muted-foreground/70 mt-6">
                    Explora los datos, analiza tendencias y obtén una visión estratégica de cara a las próximas elecciones.
                  </p>
                </motion.div>
              </div>
            </motion.div>
          </div>

          {/* Efectos decorativos de fondo */}
          <div className="absolute top-20 left-10 w-72 h-72 bg-primary/10 rounded-full blur-3xl opacity-20 animate-pulse" />
          <div className="absolute bottom-20 right-10 w-96 h-96 bg-primary/5 rounded-full blur-3xl opacity-20 animate-pulse" style={{ animationDelay: '1s' }} />
        </section>

        <section className="py-16 md:py-24 bg-primary/5" style={{backgroundImage: "url('/backgrounds/secciones b.jpeg')", backgroundSize: 'cover', backgroundPosition: 'center'}}>
          <div className="container mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold font-headline text-white tracking-tight">{c.useCasesTitle}</h2>
              <p className="mt-4 text-lg text-white/80 max-w-2xl mx-auto">{c.useCasesSubtitle}</p>
            </div>
            <Tabs defaultValue="governments" className="max-w-5xl mx-auto">
              <TabsList className="grid w-full grid-cols-2 mb-8">
                <TabsTrigger value="governments" className="text-base">{c.tabs.governments}</TabsTrigger>
                <TabsTrigger value="campaigns" className="text-base">{c.tabs.campaigns}</TabsTrigger>
              </TabsList>
              <TabsContent value="governments">
                <div className="bg-background/95 backdrop-blur rounded-2xl p-8 md:p-12">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
                    {c.govPoints.map(point => (
                      <div key={point.title} className="flex items-start gap-4">
                        <div className="flex-shrink-0 mt-1">
                          <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center">
                            <Check className="w-4 h-4 text-primary" strokeWidth={3} />
                          </div>
                        </div>
                        <div>
                          <h4 className="font-semibold text-base mb-1">{point.title}</h4>
                          <p className="text-muted-foreground text-sm leading-relaxed">{point.description}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </TabsContent>
              <TabsContent value="campaigns">
                <div className="bg-background/95 backdrop-blur rounded-2xl p-8 md:p-12">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-8">
                    {c.campaignPoints.map(point => (
                      <div key={point.title} className="flex items-start gap-4">
                        <div className="flex-shrink-0 mt-1">
                          <div className="w-6 h-6 rounded-full bg-primary/10 flex items-center justify-center">
                            <Check className="w-4 h-4 text-primary" strokeWidth={3} />
                          </div>
                        </div>
                        <div>
                          <h4 className="font-semibold text-base mb-1">{point.title}</h4>
                          <p className="text-muted-foreground text-sm leading-relaxed">{point.description}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </TabsContent>
            </Tabs>
          </div>
        </section>

        <section className="py-16 md:py-24 bg-background" style={{backgroundImage: "url('/backgrounds/cuerpo.jpeg')", backgroundSize: 'cover', backgroundPosition: 'center'}}>
          <div className="container mx-auto px-4">
            <Card className="glassmorphism-light max-w-4xl mx-auto overflow-hidden card-hud-effect">
              <div className="grid md:grid-cols-2 items-center">
                <div className="p-8">
                  <h3 className="text-2xl font-bold font-headline">{c.caseTitle}</h3>
                  <div className="prose prose-sm text-muted-foreground mt-4" dangerouslySetInnerHTML={{ __html: c.caseDescription }} />
                </div>
                <div className="relative h-64 md:h-full">
                  <Image src="/data/argentina-flag.jpg" alt="Bandera de Argentina" fill style={{objectFit: 'cover'}} data-ai-hint="Argentinian flag"/>
                </div>
              </div>
            </Card>
          </div>
        </section>

        <section className="py-16 md:py-24 bg-primary/10 text-center">
            <div className="container mx-auto px-4">
                <h2 className="text-3xl font-bold font-headline">{c.ctaTitle}</h2>
                <p className="mt-4 text-lg text-muted-foreground max-w-xl mx-auto">{c.ctaSubtitle}</p>
                <Button asChild size="lg" className="mt-8">
                    <a href={generateMailto()}>{c.ctaButton} <Mail className="ml-2"/></a>
                </Button>
            </div>
        </section>
      </main>
    </>
  );
}

    