-- AlterTable
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "provincialPartyName" TEXT;
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "CC" DOUBLE PRECISION;
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "ProFederal" DOUBLE PRECISION;
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "Potencia" DOUBLE PRECISION;
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "ProyectoSur" DOUBLE PRECISION;
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "UnionFederal" DOUBLE PRECISION;
ALTER TABLE "surveys" ADD COLUMN IF NOT EXISTS "FrenteIzquierda" DOUBLE PRECISION;
